# Generated by Django 4.2.1 on 2023-05-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='nExercise',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
