# Generated by Django 4.2.1 on 2023-05-28 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0004_alter_set_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight_Tracking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now=True)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.set')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
