# Generated by Django 4.2.1 on 2023-05-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_weight_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weight_tracking',
            name='set',
        ),
        migrations.RemoveField(
            model_name='weight_tracking',
            name='user',
        ),
        migrations.AddField(
            model_name='set',
            name='weight_tracking',
            field=models.ManyToManyField(related_name='peso', to='workouts.weight_tracking'),
        ),
    ]
