# Generated by Django 4.2.1 on 2023-05-28 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_remove_weight_tracking_set_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight_tracking',
            name='set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='weight_trackings', to='workouts.set'),
            preserve_default=False,
        ),
    ]
