# Generated by Django 4.2.1 on 2023-05-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_weight_tracking_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='nSet',
            field=models.IntegerField(default=0),
        ),
    ]
