# Generated by Django 4.2.1 on 2023-05-31 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_set_nset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reps_Tracking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reps', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reps_trackings', to='workouts.set')),
            ],
        ),
    ]
